users:
  admin:
    hostname: 127.0.0.1
    port: 8603

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  cloud:
    inetutils:
      timeout-seconds: 60
  boot:
    admin:
      client:
        instance:
          service-url: http://${users.admin.hostname}:${users.admin.port}
        period: 60000 # 每60秒 admin client 向 admin server发送心跳
        read-timeout: 60000 # 心跳注册超时时间
        connect-timeout: 60000 # 注册连接超时
        auto-registration: true # 开启自动注册

management:
  endpoints:
    web:
      exposure:
        include: '*'