server:
  port: 8602

eureka:
  user:
    hostname: 127.0.0.1
    port: 8601
  client:
  service-url:
    defaultZone: http://${eureka.user.hostname}:${eureka.user.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  rabbitmq:
    host: 10.0.228.93
    port: 30672
    username: guest
    password: guest
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace