spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  cloud:
    inetutils:
      timeout-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: '*'