server:
  port: 8302

eureka:
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
  file: logs/spring-boot-admin-client.log

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: admin-client
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'