server:
  port: 8102

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: zipkin-client-user-service
#  zipkin:
#    base-url: http://10.0.251.180:9411/
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    rabbitmq:
      addresses: 10.0.228.93:30672
      queue: zipkin
    sender:
      type: rabbit
    storage:
      type: elasticsearch
      StorageComponent: elasticsearch
      elasticsearch:
        cluster: elasticsearch
        max-requests: 30
        index: zipkin
        index-shards: 3
        index-relicas: 1
        hosts: 10.0.251.180:9200