server:
  port: 8301

eureka:
  client:
    #    register-with-eureka: false
    #    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
  file: logs/spring-boot-admin-server.log

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  application:
    name: admin-server
  boot:
    admin:
      context-path: / # server端的访问路径
      monitor:
        status-lifetime: 60000 #client端生命周期
        default-timeout: 60000 #默认超时时间
#        timeout: 60000 # 查询client的超时时间
      ui:
        title: 'a18792721831 的 admin dashboard'
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'