spring:
  # redis 服务器配置
  redis:
    host: 10.0.228.117
    port: 6379
    password: ""
    timeout: 60000
    database: 0
    # 连接池属性配置
    lettuce:
      pool:
        # 最小空闲连接数
        min-idle: 5
        # 最大空闲连接数
        max-idle: 10
        # 最大活动的连接数
        max-active: 10
        # 连接最大等待数
        max-wait: 3000
  cache:
    # 缓存相关配置
    cache-names: redisCache
#    redis:
#      # redis缓存
#      cache-null-values: true
#      # 是否允许缓存空值
#      key-prefix: x
#      # redis的键的前缀
#      time-to-live: 0ms
#      # 缓存超时时间，配置为0则表示永不超时
#      use-key-prefix: true
#      # 是否启用Redis的键前缀
    type: redis
    # 缓存类型，默认情况下，Spring会自动根据上下文探测
  datasource:
    # 配置数据库
    driver-class-name: oracle.jdbc.OracleDriver
    # 数据库驱动
    url: jdbc:oracle:thin:@//10.0.250.19:1521/starbass
    # 数据库连接
    username: system
    # 用户名
    password: system
    # 密码
    tomcat:
      # 数据库相关配置
      max-idle: 10
      # 最大闲置的连接数量
      max-active: 10
      # 最大活跃连接数量
      min-idle: 5
      # 最小闲置数量
      max-wait: 2000
      # 最大等待时间
mybatis:
  # mybatis配置
  mapper-locations: classpath:com/study/redishello/mapper/*.xml
  # mybatis的文件目录
  type-aliases-package: com.study.redishello.pojo
  # mybatis实体的包路径
logging:
  # 日志配置
  level:
    root: debug
  # 日志级别：调试
    org:
      springframework: debug
      org:
        mybatis: debug
