spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/oracle
    username: cloud
    password: cloud
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true